config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  
  # devise_scope :user do
  #   get 'registrations/show', to: "regisrations#show", as: 'user_show'
  #   # get 'session/on_signin', :to => 'sessions#memorize_session'
  # end

  root to: 'home#index'
  get 'home/show', to: 'home#show', as: 'home_show'
  resources :categories, only: :index
  resources :restaurants, only: [:index] do
    resources :foods, only: [:index, :show]
  end

  get "new_order_item", to: "order_items#new"
  resources :orders
  resources :order_items

   
  resources :carts
  resources :cart_items

  resources :admin_users, only: [:index]

  get 'account/orders', to: 'users#orders', as: 'user_orders'


  resources :addresses

  put '/addresses/:id/set_default', to: 'addresses#set_default', as: 'set_default_address'
  patch '/cart_items/:id/increment_quantity', to: 'cart_items#increment_quantity', as: 'increment_quantity'
  patch '/cart_items/:id/decrement_quantity', to: 'cart_items#decrement_quantity', as: 'decrement_quantity'

  
    # resources :cart_items do
    #   member do
    #     patch :increase_quantity
    #     patch :decrease_quantity
    #   end
    # end
  
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  scope :default, -> {where(default: true).limit(1)}
 
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :street, :city, :state, :pincode, :country, presence: true
 
  def full_address
    "#{street}, #{city}, #{state}, #{country}, #{pincode}".strip
  end 

  def name_with_email
    "#{name}(#{email})"
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :foods, through: :cart_items
  # has_one :order

  def subtotal
    cart_items.map{|item| item.quantity * item.food.price }.sum
  end
  
  def total
    subtotal + 5.0
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :food
  has_one :order_item
  # belongs_to :order
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :foods
  has_many :menu_items
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :category
  has_many :order_items
  has_many :carts, through: :cart_items
  has_one_attached :image
  belongs_to :restaurant
  # has_many :menu_items
  has_many :cart_items

  # def self.for_restaurant(restaurant_id)
  #   where(restaurant_id: restaurant_id)    
  # end
  
  # validates :quantity, numericality: { greater_than_or_equal_to: 0 }

  # def create(cart)
  #   if quantity > 0
  #     cart_item = cart.cart_items.find_by(food_id: id)
  #     if cart_item
  #       cart_item.update(quantity: cart_item.quantity + 1)
  #     else
  #       cart_item = cart.cart_items.create(food: self, quantity: 1)
  #     end
  #     update(quantity: quantity - 1)
  #     cart_item
  #   else
  #     cart_item = nil
  #     errors.add(:base, "Sorry, this item is out of stock")
  #   end
  # end
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :category
  belongs_to :food
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user
    # has_many :cart_items
    has_many :order_items, dependent: :destroy
    has_many :cart_items, through: :order_items
    # belongs_to :restaurant
    # belongs_to :address, optional: true

    # before_validation :set_address
 
    accepts_nested_attributes_for :cart_items
    
    # after_create :create_payment
    
    # validates :restaurant_id, presence: true
    # validates :default_address_id, presence: true

    enum status: [:pending, :inprogress, :complete]
    
    
    # def create_payment
    #     payement = Payment.new(order: self, user: user)
    #     payment.unpaid!
    # end
    
  
    # private
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  
  belongs_to :food
  belongs_to :order
  belongs_to :user
  has_one :cart_item
  
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
    belongs_to :order
  
    enum status: [:unpaid, :paid, :failed]

    validates :card_number, presence: true, length: { minimum: 15, maximum: 16 }
    validates :expiration_month, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 12 }
    validates :expiration_year, presence: true, numericality: { greater_than_or_equal_to: Date.today.year, less_than_or_equal_to: Date.today.year + 10 }
    validates :cvc, presence: true, length: { minimum: 3, maximum: 4 }
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # belongs_to :admin_user
  has_many :foods
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_one :cart
  # has_many :cart_items, through: :cart
  has_one :cart
  has_many :orders
  has_many :addresses
  # belongs_to :default_address, class_name: 'Address', optional: true
  # has_many :cart_items, through: :carts

  before_save :downcase_email

  validates :first_name, :last_name, presence: :true

  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true

  after_create :create_cart

  def create_cart
    build_cart.save
      # Cart.create(user: self)
  end
        
  private
    
    def downcase_email
      self.email = email.downcase
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :authenticate_user!

    def create
      @cart = current_user.cart
      
      food = Food.find(params[:food_id])
      cart_item = @cart.cart_items.where(food: food).first
      if cart_item
        cart_item.quantity += 1
        # cart_item.save!
      else
        cart_item = @cart.cart_items.build(food: food, quantity:1)
        # cart_item.save!
        # cart_item.quantity = 1
      end
      
      if cart_item.save!
        flash[:alert] = "Food added to cart"
      else
        flash[:error] = "Unable to add food to cart"
      end
      redirect_to cart_path(current_user.cart)
    end
    
    def show
        @cart_items = current_user.cart.cart_items
    end

    def update
      cart_item = current_user.cart.cart_items.find_by_id(params[:id])
      cart_item.update(quantity: (params[:cart_item][:quantity].to_f))
      redirect_to cart_path
    end
      
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
    
    before_action :authenticate_user!

    def index
        # @foods =Food.all
        @restaurant = Restaurant.find(params[:restaurant_id])
        @categories = Category.all
        
        if params[:category]
            @foods = @restaurant.foods.where(category_id:params[:category])
        else
            @foods = @restaurant.foods
        end
       
        @cart = current_user.cart
        
    end

    def authorize_restaurant!
        food = Food.find(params[:id]) 
        if current_admin_user.restaurant_id != food.restaurant_id
            flash[:error] = "You are not authorized to access"
            redirect_to root_path
        end       
    end
    

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index     
  end

  def show
    
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/active_admin.html.erb
 <%= styelesheet_link_tag 'active_admin.css' %>

app/views/sales/display.js.erb
$("#list_items").html("<%= j render 'add_food_sale' %>");

$(".sale-editable-width").change(function(){
   var food_id = $(this).data('message');
  var percentage = $(this).val();
  var food_price = $(".price_for_"+food_id).html();
  var food_sale_price = (1 - (percentage/100)) * food_price;
  $(".sale_price_"+food_id).text(food_sale_price);
});

$('#add_sale').click(function(){
  $.get("/foods");
})

app/views/shared/_form_errors.html.erb
<%# if object.errors.any? %>
  <%# <ul> %>
    <%# object.errors.full_messages.each do |message| %>
     <%# <div class="alert alert-danger" >= message</div> %>
    <%# end %>
  <%# </ul> %>
<%# end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to "Navbar", root_path, class: "navbar-brand" %>
        <%# <a class="navbar-brand" href="#">Navbar</a> %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            
             <li class="nav-item">
              <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
              <%# <a class="nav-link" href="/sign_up">Signup</a> %>
            </li>
        
            <% if current_user && current_user.cart %>
              <li><%= link_to "Cart (#{current_user.cart.cart_items.count})", cart_path(current_user.cart), class: "nav-link" %></li>
            <% end %>

           
            <%# <li class="nav-item">
              <%= link_to "Account", account_path, class: "nav-link" %>
              <%# <a class="nav-link" href="/sign_up">Signup</a> %>
            <%# </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li> %>
          </ul>

          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <% if current_user %>
            <li class="nav-item">
                <%= link_to current_user.email, home_show_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-sm btn-outline-secondary"%>
            </li>
            <% else %>
            <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-outline-dark me-md-2" %>
            </li>
            <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class:"btn btn-outline-dark me-md-2" %>
            </li>
            
            <% end %> 
          </ul>
        </div>
      </div>
</nav>