config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  
  # devise_scope :user do
  #   get 'registrations/show', to: "regisrations#show", as: 'user_show'
  #   # get 'session/on_signin', :to => 'sessions#memorize_session'
  # end

  root to: 'home#index'
  get 'home/show', to: 'home#show', as: 'home_show'
  resources :categories, only: :index
  resources :restaurants, only: [:index] do
    resources :foods, only: [:index, :show]
  end

  get "new_order_item", to: "order_items#new"
  resources :orders
  resources :order_items

   
  resources :carts
  resources :cart_items

  resources :admin_users, only: [:index]

  get 'account/orders', to: 'users#orders', as: 'user_orders'


  resources :addresses

  put '/addresses/:id/set_default', to: 'addresses#set_default', as: 'set_default_address'
  patch '/cart_items/:id/increment_quantity', to: 'cart_items#increment_quantity', as: 'increment_quantity'
  patch '/cart_items/:id/decrement_quantity', to: 'cart_items#decrement_quantity', as: 'decrement_quantity'

  
    # resources :cart_items do
    #   member do
    #     patch :increase_quantity
    #     patch :decrease_quantity
    #   end
    # end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index     
  end

  def show
    
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/customer_index.html.erb
<%= flash[:notice]%>
<div class="d-flex align-items-center justify-content-center">
   <h1>Hello User please place your order</h1>
</div>

app/views/home/index.html.erb
<%= flash[:notice]%>
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome</h1>
</div>

app/views/home/restaurant_index.html.erb
<%#= flash[:notice]%>
<div class="d-flex align-items-center justify-content-center">
    <h1>Hello Owner welcome to your Restaurant index page</h1>
</div>

<div class="container"> 
    <img src="https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" class="img-fluid" >
     <div class="d-flex align-items-center justify-content-center">
    <h1>Hello Owner welcome to your Restaurant index page</h1>
</div>
    <%# <img src="images/pexels-ash-376464.jpg"> %>
</div>

app/views/home/show.html.erb
<div class='col-lg-12'>
    <div class="card rounded-0 mt-5 mb-5">
        <div class='card-body'>
            <h2 class='text-center'>Customer Details</h2>
            <div class="row">
                <div class="col-lg-6 bg-light">
                    <h3>Personal Information</h3>
                    <p class='load'><strong>First Name: </strong><%= current_user.first_name %></p>
                    <%# <p class='load'><strong>Middle Name: </strong>= current_user.middle_name.present? ? current_user.middle_name : 'NA'</p> %>
                    <p class='load'><strong>Last Name: </strong><%= current_user.last_name %></p>
                    <p class='load'><strong>Email: </strong><%= current_user.email %></p>
                </div>
            
            </div>
            <%= link_to 'Back ',root_path, class:'btn btn-outline-primary btn-lg rounded-0'%>
            <%# <%= link_to 'Edit', edit_user_path(@user), class:'btn btn-primary btn-lg rounded-0'%> 
        </div>
    </div>
    <%= link_to 'Addresses',addresses_path, class:'btn btn-primary btn-lg rounded-0'%>
    <%= link_to 'Add Address',new_address_path, class:'btn btn-primary btn-lg rounded-0'%>
</div> 