config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  
  # devise_scope :user do
  #   get 'registrations/show', to: "regisrations#show", as: 'user_show'
  #   # get 'session/on_signin', :to => 'sessions#memorize_session'
  # end

  root to: 'home#index'
  get 'home/show', to: 'home#show', as: 'home_show'
  resources :categories, only: :index
  resources :restaurants, only: [:index] do
    resources :foods, only: [:index, :show]
  end

  get "new_order_item", to: "order_items#new"
  resources :orders
  resources :order_items

   
  resources :carts
  resources :cart_items

  resources :admin_users, only: [:index]

  get 'account/orders', to: 'users#orders', as: 'user_orders'


  resources :addresses

  put '/addresses/:id/set_default', to: 'addresses#set_default', as: 'set_default_address'
  patch '/cart_items/:id/increment_quantity', to: 'cart_items#increment_quantity', as: 'increment_quantity'
  patch '/cart_items/:id/decrement_quantity', to: 'cart_items#decrement_quantity', as: 'decrement_quantity'

  
    # resources :cart_items do
    #   member do
    #     patch :increase_quantity
    #     patch :decrease_quantity
    #   end
    # end
  
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :foods, through: :cart_items
  # has_one :order

  def subtotal
    cart_items.map{|item| item.quantity * item.food.price }.sum
  end
  
  def total
    subtotal + 5.0
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :authenticate_user!

    def create
      @cart = current_user.cart
      
      food = Food.find(params[:food_id])
      cart_item = @cart.cart_items.where(food: food).first
      if cart_item
        cart_item.quantity += 1
        # cart_item.save!
      else
        cart_item = @cart.cart_items.build(food: food, quantity:1)
        # cart_item.save!
        # cart_item.quantity = 1
      end
      
      if cart_item.save!
        flash[:alert] = "Food added to cart"
      else
        flash[:error] = "Unable to add food to cart"
      end
      redirect_to cart_path(current_user.cart)
    end
    
    def show
        @cart_items = current_user.cart.cart_items
    end

    def update
      cart_item = current_user.cart.cart_items.find_by_id(params[:id])
      cart_item.update(quantity: (params[:cart_item][:quantity].to_f))
      redirect_to cart_path
    end
      
end

app/views/carts/show.html.erb
<p class="border-top border-dark border-2 rounded-pill"></p>
<h3 class="text-center">Items Added</h3>
<p class="border-top border-dark border-2 rounded-pill"></p>
<% @cart_items.each do |cart_item| %><br/>
  <%# <div class="cart-item"> %>
  <div class="row">
  <div class="col-sm-9 p-3">
    <h4><%= cart_item.food.name %></h4> 
    <p>Price: <%= number_to_currency(cart_item.food.price) %></p> 
  </div>
  <div class="col-3 p-3 mb-2">
      <div class="btn-group" role="group" aria-label="Basic outlined example">
        <%= button_to '-', decrement_quantity_path(cart_item), method: :patch, type:"button", class:"btn btn-outline-primary" %>
        <button type="button" class="btn btn-outline-primary"><%= cart_item.quantity %></button>
        <%= button_to '+', increment_quantity_path(cart_item), method: :patch, type:"button", class:"btn btn-outline-primary" %>
      </div>
         <button  class="btn btn-danger" id="<%=cart_item.id%>", onclick="delete_cart_item(this)">Delete</button>
      <br/><br/>
    </div>
    </div>
<% end %><br/>
 <%= link_to "Add More Item", restaurants_path, class: "btn btn-info" %> 
<br><br>
<p class="border-top border-dark border-2 rounded-pill"></p>
<h3 class="text-center">Bill Summary</h3>
<p class="border-top border-dark border-2 rounded-pill"></p>
<% if current_user.cart.cart_items %>
  <table class="table">
    <thead >
      <tr>
        <th scope="col">Product</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
      <% current_user.cart.cart_items.each do |item| %>
        <tr>
          <td ><%= item.food.name %></td>
          <td><%= item.quantity %></td>
          <td><%= (item.food.price * item.quantity) %></td>
        </tr>
      <% end %>
      <tr>
        <td colspan="2">Subtotal:</td>
        <td><%= (current_user.cart.subtotal) %></td>
      </tr>
      <tr>
        <td colspan="2">Total:</td>
        <td><%=(current_user.cart.total) %></td>
      </tr>
    </tbody>
  </table>
<% else %>
  <p>Your cart is empty.</p>
<% end %>
<p class="border-top border-dark border-2 rounded-pill"></p>
<h3 class="text-center">Your Details</h3>
<p class="border-top border-dark border-2 rounded-pill"></p>
<%= current_user.addresses.default.first.name %><br/>
<%= current_user.addresses.default.first.email %><br/>
<%= current_user.addresses.default.first.full_address %>
<br/><br/>
<%= link_to 'Addresses',addresses_path, class:'link-underline-light"'%>
<br/><br/>
<%= button_to "Place Order", orders_path(total_amount: current_user.cart.total, order_items: current_user.cart.cart_items), method: :post, class: "btn btn-primary d-grid gap-2" %><br/>


<script>
  function delete_cart_item(e) {
    // debugger
    var url = "/cart_items/" + e.id
    // console.log(url)
    // debugger

    $.ajax({
      url: url,
      method: 'delete', 
      dataType: "json",
      success:function(data) {
        if(data.message == 'success') {
          // console.log(document.getElementById(data.body.id));          
          document.getElementById(data.body.id)
          e.parentElement.parentElement.remove();
        }
      }
    })
  }
</script>